export const ERROR_GETTING_CARDS = "ERROR_GETTING_CARDS";
export const SUCCESS_GETTING_CARDS = "SUCCESS_GETTING_CARDS";
export const LOADING_GETTING_CARDS = "LOADING_GETTING_CARDS";
export const SET_CHOSEN_CARD = "SET_CHOSEN_CARD";
export const INCREASE_OFFSET = "INCREASE_OFFSET";
export const REDUCE_OFFSET = "REDUCE_OFFSET";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const TOTAL_CARDS_COUNT = "TOTAL_CARDS_COUNT";

