export const ERROR_GETTING_CARDS = "ERROR_GETTING_CARDS";
export const SUCCESS_GETTING_CARDS = "SUCCESS_GETTING_CARDS";
export const LOADING_GETTING_CARDS = "LOADING_GETTING_CARDS";
export const SET_CHOSEN_CARD = "SET_CHOSEN_CARD";